// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mediapipe/util/tracking/tracked_detection_manager_config.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_mediapipe_2futil_2ftracking_2ftracked_5fdetection_5fmanager_5fconfig_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_mediapipe_2futil_2ftracking_2ftracked_5fdetection_5fmanager_5fconfig_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3015000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3015008 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_mediapipe_2futil_2ftracking_2ftracked_5fdetection_5fmanager_5fconfig_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_mediapipe_2futil_2ftracking_2ftracked_5fdetection_5fmanager_5fconfig_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_mediapipe_2futil_2ftracking_2ftracked_5fdetection_5fmanager_5fconfig_2eproto;
namespace mediapipe {
class TrackedDetectionManagerConfig;
struct TrackedDetectionManagerConfigDefaultTypeInternal;
extern TrackedDetectionManagerConfigDefaultTypeInternal _TrackedDetectionManagerConfig_default_instance_;
}  // namespace mediapipe
PROTOBUF_NAMESPACE_OPEN
template<> ::mediapipe::TrackedDetectionManagerConfig* Arena::CreateMaybeMessage<::mediapipe::TrackedDetectionManagerConfig>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace mediapipe {

// ===================================================================

class TrackedDetectionManagerConfig PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mediapipe.TrackedDetectionManagerConfig) */ {
 public:
  inline TrackedDetectionManagerConfig() : TrackedDetectionManagerConfig(nullptr) {}
  ~TrackedDetectionManagerConfig() override;
  explicit constexpr TrackedDetectionManagerConfig(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TrackedDetectionManagerConfig(const TrackedDetectionManagerConfig& from);
  TrackedDetectionManagerConfig(TrackedDetectionManagerConfig&& from) noexcept
    : TrackedDetectionManagerConfig() {
    *this = ::std::move(from);
  }

  inline TrackedDetectionManagerConfig& operator=(const TrackedDetectionManagerConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline TrackedDetectionManagerConfig& operator=(TrackedDetectionManagerConfig&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TrackedDetectionManagerConfig& default_instance() {
    return *internal_default_instance();
  }
  static inline const TrackedDetectionManagerConfig* internal_default_instance() {
    return reinterpret_cast<const TrackedDetectionManagerConfig*>(
               &_TrackedDetectionManagerConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(TrackedDetectionManagerConfig& a, TrackedDetectionManagerConfig& b) {
    a.Swap(&b);
  }
  inline void Swap(TrackedDetectionManagerConfig* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TrackedDetectionManagerConfig* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline TrackedDetectionManagerConfig* New() const final {
    return CreateMaybeMessage<TrackedDetectionManagerConfig>(nullptr);
  }

  TrackedDetectionManagerConfig* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<TrackedDetectionManagerConfig>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const TrackedDetectionManagerConfig& from);
  void MergeFrom(const TrackedDetectionManagerConfig& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TrackedDetectionManagerConfig* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mediapipe.TrackedDetectionManagerConfig";
  }
  protected:
  explicit TrackedDetectionManagerConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIsSameDetectionMaxAreaRatioFieldNumber = 1,
    kIsSameDetectionMinOverlapRatioFieldNumber = 2,
  };
  // optional float is_same_detection_max_area_ratio = 1 [default = 3];
  bool has_is_same_detection_max_area_ratio() const;
  private:
  bool _internal_has_is_same_detection_max_area_ratio() const;
  public:
  void clear_is_same_detection_max_area_ratio();
  float is_same_detection_max_area_ratio() const;
  void set_is_same_detection_max_area_ratio(float value);
  private:
  float _internal_is_same_detection_max_area_ratio() const;
  void _internal_set_is_same_detection_max_area_ratio(float value);
  public:

  // optional float is_same_detection_min_overlap_ratio = 2 [default = 0.5];
  bool has_is_same_detection_min_overlap_ratio() const;
  private:
  bool _internal_has_is_same_detection_min_overlap_ratio() const;
  public:
  void clear_is_same_detection_min_overlap_ratio();
  float is_same_detection_min_overlap_ratio() const;
  void set_is_same_detection_min_overlap_ratio(float value);
  private:
  float _internal_is_same_detection_min_overlap_ratio() const;
  void _internal_set_is_same_detection_min_overlap_ratio(float value);
  public:

  // @@protoc_insertion_point(class_scope:mediapipe.TrackedDetectionManagerConfig)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  float is_same_detection_max_area_ratio_;
  float is_same_detection_min_overlap_ratio_;
  friend struct ::TableStruct_mediapipe_2futil_2ftracking_2ftracked_5fdetection_5fmanager_5fconfig_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TrackedDetectionManagerConfig

// optional float is_same_detection_max_area_ratio = 1 [default = 3];
inline bool TrackedDetectionManagerConfig::_internal_has_is_same_detection_max_area_ratio() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool TrackedDetectionManagerConfig::has_is_same_detection_max_area_ratio() const {
  return _internal_has_is_same_detection_max_area_ratio();
}
inline void TrackedDetectionManagerConfig::clear_is_same_detection_max_area_ratio() {
  is_same_detection_max_area_ratio_ = 3;
  _has_bits_[0] &= ~0x00000001u;
}
inline float TrackedDetectionManagerConfig::_internal_is_same_detection_max_area_ratio() const {
  return is_same_detection_max_area_ratio_;
}
inline float TrackedDetectionManagerConfig::is_same_detection_max_area_ratio() const {
  // @@protoc_insertion_point(field_get:mediapipe.TrackedDetectionManagerConfig.is_same_detection_max_area_ratio)
  return _internal_is_same_detection_max_area_ratio();
}
inline void TrackedDetectionManagerConfig::_internal_set_is_same_detection_max_area_ratio(float value) {
  _has_bits_[0] |= 0x00000001u;
  is_same_detection_max_area_ratio_ = value;
}
inline void TrackedDetectionManagerConfig::set_is_same_detection_max_area_ratio(float value) {
  _internal_set_is_same_detection_max_area_ratio(value);
  // @@protoc_insertion_point(field_set:mediapipe.TrackedDetectionManagerConfig.is_same_detection_max_area_ratio)
}

// optional float is_same_detection_min_overlap_ratio = 2 [default = 0.5];
inline bool TrackedDetectionManagerConfig::_internal_has_is_same_detection_min_overlap_ratio() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool TrackedDetectionManagerConfig::has_is_same_detection_min_overlap_ratio() const {
  return _internal_has_is_same_detection_min_overlap_ratio();
}
inline void TrackedDetectionManagerConfig::clear_is_same_detection_min_overlap_ratio() {
  is_same_detection_min_overlap_ratio_ = 0.5f;
  _has_bits_[0] &= ~0x00000002u;
}
inline float TrackedDetectionManagerConfig::_internal_is_same_detection_min_overlap_ratio() const {
  return is_same_detection_min_overlap_ratio_;
}
inline float TrackedDetectionManagerConfig::is_same_detection_min_overlap_ratio() const {
  // @@protoc_insertion_point(field_get:mediapipe.TrackedDetectionManagerConfig.is_same_detection_min_overlap_ratio)
  return _internal_is_same_detection_min_overlap_ratio();
}
inline void TrackedDetectionManagerConfig::_internal_set_is_same_detection_min_overlap_ratio(float value) {
  _has_bits_[0] |= 0x00000002u;
  is_same_detection_min_overlap_ratio_ = value;
}
inline void TrackedDetectionManagerConfig::set_is_same_detection_min_overlap_ratio(float value) {
  _internal_set_is_same_detection_min_overlap_ratio(value);
  // @@protoc_insertion_point(field_set:mediapipe.TrackedDetectionManagerConfig.is_same_detection_min_overlap_ratio)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace mediapipe

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_mediapipe_2futil_2ftracking_2ftracked_5fdetection_5fmanager_5fconfig_2eproto
