# MediaPipe graph that performs face mesh with TensorFlow Lite on CPU.

# origin from: mediapipe/graphs/object_detection_3d/objection_desktop_cpu.pbtxt

# Input image. (ImageFrame)
input_stream: "input_video"

# user input. keyboard and mouse
#input_stream: "user_input"

# Output image with rendered results. (ImageFrame)
output_stream: "output_video"

# Throttles the images flowing downstream for flow control. It passes through
# the very first incoming image unaltered, and waits for downstream nodes
# (calculators and subgraphs) in the graph to finish their tasks before it
# passes through another image. All images that come in while waiting are
# dropped, limiting the number of in-flight images in most part of the graph to
# 1. This prevents the downstream nodes from queuing up incoming images and data
# excessively, which leads to increased latency and memory usage, unwanted in
# real-time mobile applications. It also eliminates unnecessarily computation,
# e.g., the output produced by a node may get dropped downstream if the
# subsequent nodes are still busy processing previous inputs.
node {
  calculator: "FlowLimiterCalculator"
  input_stream: "input_video"
  input_stream: "FINISHED:output_video"
  input_stream_info: {
    tag_index: "FINISHED"
    back_edge: true
  }
  output_stream: "throttled_input_video"
}

# Run Objectron subgraph.
node {
  calculator: "ObjectronCpuSubgraph"
  input_stream: "IMAGE:throttled_input_video"
  input_side_packet: "MODEL_PATH:box_landmark_model_path"
  input_side_packet: "LABELS_CSV:allowed_labels"
  input_side_packet: "MAX_NUM_OBJECTS:max_num_objects"
  output_stream: "MULTI_LANDMARKS:box_landmarks"
  output_stream: "NORM_RECTS:box_rect"
}

# Subgraph that renders annotations and overlays them on top of the input
# images (see renderer_cpu.pbtxt).
node {
  calculator: "RendererSubgraph"
  input_stream: "IMAGE:throttled_input_video"
  input_stream: "MULTI_LANDMARKS:box_landmarks"
  input_stream: "NORM_RECTS:box_rect"
  output_stream: "IMAGE:output_video"
}